
[[constraint]]
  name = "github.com/awalterschulze/gographviz"
  version = "1.0.0"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btclog"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/decred/dcrd"


[[constraint]]
  branch = "master"
  name = "github.com/decred/dcrwallet"

[[constraint]]
  branch = "master"
  name = "github.com/jrick/logrotate"

[[constraint]]
  branch = "master"
  name = "github.com/tv42/zbase32"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.18.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.5.2"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/macaroon.v1"

[prune]
  go-tests = true
  unused-packages = true
